SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE table errand;
TRUNCATE table external_tag;
TRUNCATE table attachment;
TRUNCATE table stakeholder;
TRUNCATE table contact_channel;
TRUNCATE table category;
TRUNCATE table external_id_type;
TRUNCATE table status;
TRUNCATE table role;
TRUNCATE table `type`;
TRUNCATE table validation;
TRUNCATE table revision;
TRUNCATE table attachment_data;
TRUNCATE table errand_number_sequence;
TRUNCATE table label;
TRUNCATE table communication;
TRUNCATE table communication_attachment;
TRUNCATE table communication_attachment_data;
TRUNCATE table communication_email_header;
TRUNCATE table communication_email_header_value;
TRUNCATE table notification;
TRUNCATE table parameter;
TRUNCATE table contact_reason;
SET FOREIGN_KEY_CHECKS = 1;
