SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE table errand;
TRUNCATE table external_tag;
TRUNCATE table attachment;
TRUNCATE table stakeholder;
TRUNCATE table contact_channel;
TRUNCATE table category_tag;
TRUNCATE table external_id_type_tag;
TRUNCATE table status_tag;
TRUNCATE table type_tag;
TRUNCATE table tag_validation;
SET FOREIGN_KEY_CHECKS = 1;