integration:
  emailreader:
    url: http://localhost:${wiremock.server.port:}/api-emailreader
  employee:
    url: http://localhost:${wiremock.server.port:}/api-employee
  eventlog:
    url: http://localhost:${wiremock.server.port:}/api-eventlog
  messaging:
    url: http://localhost:${wiremock.server.port:}/api-messaging
  messageexchange:
    url: http://localhost:${wiremock.server.port:}/api-messageexchange
  messaging-settings:
    url: http://localhost:${wiremock.server.port:}/api-messaging-settings
  notes:
    url: http://localhost:${wiremock.server.port:}/api-notes
  web-message-collector:
    url: http://localhost:${wiremock.server.port:}/api-web-message-collector
  citizen:
    url: http://localhost:${wiremock.server.port:}/api-citizen
  relation:
    url: http://localhost:${wiremock.server.port:}/api-relation
scheduler:
  emailreader:
    cron: "-"
  web-message-collector:
    cron: "-"
  notification:
    cron: "-"
  messageexchange:
    cron: "-"
    enabled: false
spring:
  cache:
    type: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///ittest
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
  security:
    oauth2:
      client:
        provider:
          emailreader:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          employee:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          eventlog:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          messaging:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          messageexchange:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          messaging-settings:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          notes:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          web-message-collector:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          citizen:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          relation:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          emailreader:
            client-id: the-client-id
            client-secret: the-client-secret
          employee:
            client-id: the-client-id
            client-secret: the-client-secret
          eventlog:
            client-id: the-client-id
            client-secret: the-client-secret
          messaging:
            client-id: the-client-id
            client-secret: the-client-secret
          messageexchange:
            client-id: the-client-id
            client-secret: the-client-secret
          messaging-settings:
            client-id: the-client-id
            client-secret: the-client
          notes:
            client-id: the-client-id
            client-secret: the-client-secret
          web-message-collector:
            client-id: the-client-id
            client-secret: the-client-secret
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          relation:
            client-id: the-client-id
            client-secret: the-client-secret
