openapi: 3.0.1
info:
  title: access-mapper
  contact: {}
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: '@project.version@'
tags:
- name: Access Group
  description: Access Group resources
- name: Access configuration
  description: Access configuration resources
paths:
  /{municipalityId}/{namespace}/access-config/group/{groupId}:
    get:
      tags:
      - Access Group
      operationId: getAccessGroup
      parameters:
      - name: municipalityId
        in: path
        description: Municipality ID
        required: true
        schema:
          type: string
        example: 2281
      - name: namespace
        in: path
        description: Namespace
        required: true
        schema:
          pattern: "[\\w|\\-]+"
          type: string
        example: MY_NAMESPACE
      - name: groupId
        in: path
        description: Group ID
        required: true
        schema:
          minLength: 1
          type: string
        example: group123
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessGroup"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: "#/components/schemas/Problem"
                - $ref: "#/components/schemas/ConstraintViolationProblem"
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
    put:
      tags:
      - Access Group
      operationId: updateAccessGroup
      parameters:
      - name: municipalityId
        in: path
        description: Municipality ID
        required: true
        schema:
          type: string
        example: 2281
      - name: namespace
        in: path
        description: Namespace
        required: true
        schema:
          pattern: "[\\w|\\-]+"
          type: string
        example: MY_NAMESPACE
      - name: groupId
        in: path
        description: Group ID
        required: true
        schema:
          minLength: 1
          type: string
        example: group123
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccessGroup"
        required: true
      responses:
        "204":
          description: No content - Successful operation
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: "#/components/schemas/Problem"
                - $ref: "#/components/schemas/ConstraintViolationProblem"
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
    post:
      tags:
      - Access Group
      operationId: createAccessGroup
      parameters:
      - name: municipalityId
        in: path
        description: Municipality ID
        required: true
        schema:
          type: string
        example: 2281
      - name: namespace
        in: path
        description: Namespace
        required: true
        schema:
          pattern: "[\\w|\\-]+"
          type: string
        example: MY_NAMESPACE
      - name: groupId
        in: path
        description: Group ID
        required: true
        schema:
          minLength: 1
          type: string
        example: group123
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccessGroup"
        required: true
      responses:
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: "#/components/schemas/Problem"
                - $ref: "#/components/schemas/ConstraintViolationProblem"
            '*/*':
              schema:
                $ref: "#/components/schemas/AccessGroup"
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
            '*/*':
              schema:
                $ref: "#/components/schemas/AccessGroup"
        "201":
          description: Successfully created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AccessGroup"
    delete:
      tags:
      - Access Group
      operationId: deleteAccessGroup
      parameters:
      - name: municipalityId
        in: path
        description: Municipality ID
        required: true
        schema:
          type: string
        example: 2281
      - name: namespace
        in: path
        description: Namespace
        required: true
        schema:
          pattern: "[\\w|\\-]+"
          type: string
        example: MY_NAMESPACE
      - name: groupId
        in: path
        description: Group ID
        required: true
        schema:
          minLength: 1
          type: string
        example: group123
      responses:
        "204":
          description: No content - Successful operation
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: "#/components/schemas/Problem"
                - $ref: "#/components/schemas/ConstraintViolationProblem"
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /{municipalityId}/{namespace}/access/ad/{adId}:
    get:
      tags:
      - Access configuration
      operationId: getAccessDetails
      parameters:
      - name: municipalityId
        in: path
        description: Municipality ID
        required: true
        schema:
          type: string
        example: 2281
      - name: namespace
        in: path
        description: Namespace
        required: true
        schema:
          pattern: "[\\w|\\-]+"
          type: string
        example: MY_NAMESPACE
      - name: adId
        in: path
        description: AdId for the user to get details about
        required: true
        schema:
          type: string
        example: joe01doe
      - name: type
        in: query
        description: Filter type
        required: false
        schema:
          type: string
        example: label
      responses:
        "200":
          description: Successful operation
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AccessGroup"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: "#/components/schemas/Problem"
                - $ref: "#/components/schemas/ConstraintViolationProblem"
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /{municipalityId}/{namespace}/access-config/group:
    get:
      tags:
      - Access Group
      operationId: getAccessGroups
      parameters:
      - name: municipalityId
        in: path
        description: Municipality ID
        required: true
        schema:
          type: string
        example: 2281
      - name: namespace
        in: path
        description: Namespace
        required: true
        schema:
          pattern: "[\\w|\\-]+"
          type: string
        example: MY_NAMESPACE
      - name: type
        in: query
        description: Filter type
        required: false
        schema:
          type: string
        example: label
      responses:
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: "#/components/schemas/Problem"
                - $ref: "#/components/schemas/ConstraintViolationProblem"
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AccessGroup"
  /api-docs:
    get:
      tags:
      - API
      summary: OpenAPI
      operationId: getApiDocs
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-mutual-ssl: Optional
components:
  schemas:
    Access:
      type: object
      properties:
        pattern:
          type: string
          description: Access pattern
          example: FA/**
        accessLevel:
          type: string
          description: Access level
          example: LR
          enum:
          - RW
          - R
          - LR
      description: Access model
    AccessGroup:
      type: object
      properties:
        group:
          type: string
          description: Access group
          example: G1
        accessByType:
          type: array
          description: Access by type
          items:
            $ref: "#/components/schemas/AccessType"
      description: Access group model
    AccessType:
      type: object
      properties:
        type:
          type: string
          description: Access type
          example: label
        access:
          type: array
          description: Access by type
          items:
            $ref: "#/components/schemas/Access"
      description: Access type model
    Problem:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/StatusType"
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        detail:
          type: string
        title:
          type: string
    StatusType:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        reasonPhrase:
          type: string
    ConstraintViolationProblem:
      type: object
      properties:
        cause:
          $ref: "#/components/schemas/ThrowableProblem"
        stackTrace:
          type: array
          items:
            type: object
            properties:
              classLoaderName:
                type: string
              moduleName:
                type: string
              moduleVersion:
                type: string
              methodName:
                type: string
              fileName:
                type: string
              lineNumber:
                type: integer
                format: int32
              className:
                type: string
              nativeMethod:
                type: boolean
        type:
          type: string
          format: uri
        status:
          $ref: "#/components/schemas/StatusType"
        violations:
          type: array
          items:
            $ref: "#/components/schemas/Violation"
        title:
          type: string
        message:
          type: string
        instance:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        detail:
          type: string
        suppressed:
          type: array
          items:
            type: object
            properties:
              stackTrace:
                type: array
                items:
                  type: object
                  properties:
                    classLoaderName:
                      type: string
                    moduleName:
                      type: string
                    moduleVersion:
                      type: string
                    methodName:
                      type: string
                    fileName:
                      type: string
                    lineNumber:
                      type: integer
                      format: int32
                    className:
                      type: string
                    nativeMethod:
                      type: boolean
              message:
                type: string
              localizedMessage:
                type: string
        localizedMessage:
          type: string
    ThrowableProblem:
      type: object
      properties:
        cause:
          $ref: "#/components/schemas/ThrowableProblem"
        stackTrace:
          type: array
          items:
            type: object
            properties:
              classLoaderName:
                type: string
              moduleName:
                type: string
              moduleVersion:
                type: string
              methodName:
                type: string
              fileName:
                type: string
              lineNumber:
                type: integer
                format: int32
              className:
                type: string
              nativeMethod:
                type: boolean
        message:
          type: string
        status:
          $ref: "#/components/schemas/StatusType"
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        detail:
          type: string
        title:
          type: string
        suppressed:
          type: array
          items:
            type: object
            properties:
              stackTrace:
                type: array
                items:
                  type: object
                  properties:
                    classLoaderName:
                      type: string
                    moduleName:
                      type: string
                    moduleVersion:
                      type: string
                    methodName:
                      type: string
                    fileName:
                      type: string
                    lineNumber:
                      type: integer
                      format: int32
                    className:
                      type: string
                    nativeMethod:
                      type: boolean
              message:
                type: string
              localizedMessage:
                type: string
        localizedMessage:
          type: string
    Violation:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
  securitySchemes: {}
