openapi: 3.0.1
info:
  title: Employee API
  version: v2
paths:
  '/api/v2/employee/{municipalityId}/api-docs':
    get:
      tags:
        - Employee
      summary: OpenAPI specification
      parameters:
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
      x-auth-type: None
  '/api/v2/employee/{municipalityId}/employed/{personId}/accounts':
    get:
      tags:
        - Employee
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/api/v2/employee/{municipalityId}/portalpersondata/{domain}/{loginName}':
    get:
      tags:
        - Employee
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: loginName
          in: path
          required: true
          schema:
            type: string
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PortalPersonData'
            application/json:
              schema:
                $ref: '#/components/schemas/PortalPersonData'
            text/json:
              schema:
                $ref: '#/components/schemas/PortalPersonData'
  '/api/v2/employee/{municipalityId}/portalpersondata/{email}':
    get:
      tags:
        - Employee
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PortalPersonData'
            application/json:
              schema:
                $ref: '#/components/schemas/PortalPersonData'
            text/json:
              schema:
                $ref: '#/components/schemas/PortalPersonData'
  '/api/v2/employee/{municipalityId}/employments':
    get:
      tags:
        - Employee
      parameters:
        - name: CompanyId
          in: query
          description: Filtrera en eller flera CompanyId
          schema:
            type: array
            items:
              type: integer
              format: int32
        - name: HireDateFrom
          in: query
          description: Filtrera på anställningsdatum från och med
          schema:
            type: string
            format: date
            example: '2023-01-01'
        - name: HireDateTo
          in: query
          description: Filtrera på anställningsdatum till och med
          schema:
            type: string
            format: date
            example: '2023-01-01'
        - name: IsManual
          in: query
          description: Filtrera på manuella eller vanliga anställningar
          schema:
            type: integer
            format: int32
        - name: PersonId
          in: query
          description: Filtrera på personId
          schema:
            type: string
            format: uuid
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employeev2'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employeev2'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employeev2'
  '/api/v2/employee/{municipalityId}/newemployments':
    get:
      tags:
        - Employee
      parameters:
        - name: CompanyId
          in: query
          description: Filtrera en eller flera CompanyId
          schema:
            type: array
            items:
              type: integer
              format: int32
        - name: HireDateFrom
          in: query
          description: Filtrera på anställningsdatum från och med
          schema:
            type: string
            format: date
            example: '2023-01-01'
        - name: HireDateTo
          in: query
          description: Filtrera på anställningsdatum till och med
          schema:
            type: string
            format: date
            example: '2023-01-01'
        - name: EventInfo
          in: query
          description: 'Filtrera på eventinfo: "Company","Rehire,Company","Corporate","Rehire,Corporate","Mover","Jumper"'
          schema:
            type: array
            items:
              type: string
        - name: Title
          in: query
          description: Filtrera på anställningstitel
          schema:
            type: string
        - name: PersonId
          in: query
          description: Filtrera personId
          schema:
            type: string
            format: uuid
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewEmployee'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewEmployee'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewEmployee'
  '/api/v2/employee/{municipalityId}/{personId}/personimage':
    get:
      tags:
        - Employee
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: width
          in: query
          schema:
            type: integer
            format: int32
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
    put:
      tags:
        - Employee
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelPostPersonImage'
          text/json:
            schema:
              $ref: '#/components/schemas/ModelPostPersonImage'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ModelPostPersonImage'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Employee
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  '/api/v2/employee/{municipalityId}/manageremployees/{managerId}':
    get:
      tags:
        - Employee
      parameters:
        - name: managerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ManagerEmployee'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ManagerEmployee'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ManagerEmployee'
components:
  schemas:
    Account:
      type: object
      properties:
        domain:
          type: string
          nullable: true
        loginname:
          type: string
          nullable: true
        companyId:
          type: integer
          format: int32
        emailAddress:
          type: string
          nullable: true
      additionalProperties: false
    Employeev2:
      type: object
      properties:
        personId:
          type: string
          format: uuid
        personNumber:
          type: string
          nullable: true
        isClassified:
          type: boolean
        givenname:
          type: string
          nullable: true
        middlename:
          type: string
          nullable: true
        lastname:
          type: string
          nullable: true
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'
          nullable: true
        referenceNumbers:
          type: array
          items:
            $ref: '#/components/schemas/ReferenceNumberCompany'
          nullable: true
        employments:
          type: array
          items:
            $ref: '#/components/schemas/Employment'
          nullable: true
      additionalProperties: false
    Employment:
      type: object
      properties:
        companyId:
          type: integer
          format: int32
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
          nullable: true
        employmentType:
          type: integer
          format: int32
        title:
          type: string
          nullable: true
        managerCode:
          type: string
          nullable: true
        orgId:
          type: integer
          format: int32
        orgName:
          type: string
          nullable: true
        topOrgId:
          type: integer
          format: int32
        topOrgName:
          type: string
          nullable: true
        benefitGroupId:
          type: integer
          format: int32
          nullable: true
        formOfEmploymentId:
          type: string
          nullable: true
        isManual:
          type: boolean
        paTeam:
          type: string
          nullable: true
        isMainEmployment:
          type: boolean
        isManager:
          type: boolean
          nullable: true
        manager:
          $ref: '#/components/schemas/Manager'
        aid:
          type: string
          nullable: true
        empRowId:
          type: string
          nullable: true
      additionalProperties: false
    Manager:
      type: object
      properties:
        personId:
          type: string
          format: uuid
        givenname:
          type: string
          nullable: true
        middlename:
          type: string
          nullable: true
        lastname:
          type: string
          nullable: true
        loginname:
          type: string
          nullable: true
        emailAddress:
          type: string
          nullable: true
        referenceNumber:
          type: string
          nullable: true
      additionalProperties: false
    ManagerEmployee:
      type: object
      properties:
        personId:
          type: string
          format: uuid
        hireDate:
          type: string
          format: date-time
          nullable: true
        retireDate:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false
    ModelPostPersonImage:
      type: object
      properties:
        title:
          type: string
          nullable: true
        imageData:
          type: string
          nullable: true
      additionalProperties: false
    NewEmployee:
      type: object
      properties:
        personId:
          type: string
          format: uuid
        personNumber:
          type: string
          nullable: true
        isClassified:
          type: boolean
        givenname:
          type: string
          nullable: true
        middlename:
          type: string
          nullable: true
        lastname:
          type: string
          nullable: true
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'
          nullable: true
        referenceNumbers:
          type: array
          items:
            $ref: '#/components/schemas/ReferenceNumberCompany'
          nullable: true
        employments:
          type: array
          items:
            $ref: '#/components/schemas/NewEmployment'
          nullable: true
      additionalProperties: false
    NewEmployment:
      type: object
      properties:
        companyId:
          type: integer
          format: int32
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
          nullable: true
        employmentType:
          type: integer
          format: int32
        title:
          type: string
          nullable: true
        managerCode:
          type: string
          nullable: true
        orgId:
          type: integer
          format: int32
        orgName:
          type: string
          nullable: true
        topOrgId:
          type: integer
          format: int32
        topOrgName:
          type: string
          nullable: true
        benefitGroupId:
          type: integer
          format: int32
          nullable: true
        formOfEmploymentId:
          type: string
          nullable: true
        isManual:
          type: boolean
        paTeam:
          type: string
          nullable: true
        isMainEmployment:
          type: boolean
        isManager:
          type: boolean
          nullable: true
        manager:
          $ref: '#/components/schemas/Manager'
        aid:
          type: string
          nullable: true
        empRowId:
          type: string
          nullable: true
        eventType:
          type: string
          nullable: true
        eventInfo:
          type: string
          nullable: true
      additionalProperties: false
    PortalPersonData:
      type: object
      properties:
        personid:
          type: string
          format: uuid
        givenname:
          type: string
          nullable: true
        lastname:
          type: string
          nullable: true
        fullname:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        postalCode:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        workPhone:
          type: string
          nullable: true
        mobilePhone:
          type: string
          nullable: true
        extraMobilePhone:
          type: string
          nullable: true
        aboutMe:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        mailNickname:
          type: string
          nullable: true
        company:
          type: string
          nullable: true
        companyId:
          type: integer
          format: int32
        orgTree:
          type: string
          nullable: true
        referenceNumber:
          type: string
          nullable: true
        isManager:
          type: boolean
        loginName:
          type: string
          nullable: true
        fullOrgTree:
          type: string
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }
    ReferenceNumberCompany:
      type: object
      properties:
        referenceNumber:
          type: string
          nullable: true
        companyId:
          type: integer
          format: int32
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: JWT Authorization header using the Bearer scheme.
      name: X-JWT-Assertion
      in: header
security:
  - Bearer: [ ]
tags:
  - name: Employee
    description: Handles information about employees