version: "3"
services:
  ms-notes-sandbox:
    container_name: ms-support-management-sandbox
    image: 'ms-support-management'
    network_mode: bridge
    links:
      - 'ms-support-management-db-sandbox:mariadb'
    restart: always
    build:
      context: ../../..
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "1337:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'sandbox'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://ms-support-management-db-sandbox:3306/supportmanagement'
      SPRING_DATASOURCE_USERNAME: 'sandbox-user'
      SPRING_DATASOURCE_PASSWORD: 'sandbox-password'
    depends_on:
      - ms-support-management-db-sandbox

  ms-support-management-db-sandbox:
    container_name: ms-support-management-db-sandbox
    image: 'mariadb:10.6.4'
    network_mode: bridge
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD : 'yes'
      MARIADB_DATABASE: 'supportmanagement'
      MARIADB_USER: 'sandbox-user'
      MARIADB_PASSWORD: 'sandbox-password'
    expose:
      - '3306'