name: Diff API documentation

on:
  pull_request_target:
    branches:
      - 9.0 # ← Change this to the name of your target main branch

jobs:
  public-api-diff:
    if: ${{ github.event_name == 'pull_request_target' }}
    name: Check public API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          file: src/test/resources/api/openapi.yaml # ← Change this to the path of your API contract file
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
